# Generated by Django 5.0.7 on 2025-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='$', max_length=3, verbose_name='Символ'),
        ),
    ]
