# Generated by Django 5.0.7 on 2025-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_crypto',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
