# Generated by Django 5.0.7 on 2025-03-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_amount_crypto_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип тарифа',
                'verbose_name_plural': 'Типы тарифов',
            },
        ),
        migrations.AddField(
            model_name='tariff',
            name='can_change_avatar_color',
            field=models.BooleanField(default=False, verbose_name='Можно менять цвет аватарки'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='can_change_nickname',
            field=models.BooleanField(default=False, verbose_name='Можно менять никнейм'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='site_name',
            field=models.CharField(default='', max_length=20, verbose_name='Название на сайте'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='tariff_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.tarifftype'),
        ),
    ]
