# Generated by Django 5.0.7 on 2025-03-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_tarifftype_tariff_can_change_avatar_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='tariff_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.tarifftype', verbose_name='Тип тарифа'),
        ),
    ]
