# Generated by Django 5.0.7 on 2024-11-18 15:45

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_magic_room', '0002_journal_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achivments',
            options={'verbose_name': 'Награда', 'verbose_name_plural': 'Награды'},
        ),
        migrations.AlterModelOptions(
            name='memes',
            options={'verbose_name': 'Мем', 'verbose_name_plural': 'Мемы'},
        ),
        migrations.AlterField(
            model_name='achivments',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='content',
            field=django_quill.fields.QuillField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='page_number',
            field=models.PositiveIntegerField(verbose_name='Номер страницы'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='memes',
            name='anonce',
            field=models.TextField(blank=True, default='', verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='memes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='memes',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='anonce',
            field=models.TextField(blank=True, default='', verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tales',
            name='anonce',
            field=models.TextField(blank=True, default='', verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='tales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='tales',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
