# Generated by Django 5.0.7 on 2024-11-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiparametrs',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='chatcontext',
            options={'verbose_name': 'Контекст', 'verbose_name_plural': 'Контексты'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Интерес', 'verbose_name_plural': 'Интересы'},
        ),
        migrations.AlterModelOptions(
            name='interestcategory',
            options={'verbose_name': 'Категория интересов', 'verbose_name_plural': 'Категории интересов'},
        ),
        migrations.AlterModelOptions(
            name='userinterest',
            options={'verbose_name': 'Интерес пользователя', 'verbose_name_plural': 'Интересы пользователей'},
        ),
        migrations.AlterField(
            model_name='aiparametrs',
            name='character',
            field=models.TextField(verbose_name='Характер'),
        ),
        migrations.AlterField(
            model_name='aiparametrs',
            name='temperature',
            field=models.FloatField(choices=[(0.1, '0.1'), (0.2, '0.2'), (0.3, '0.3'), (0.4, '0.4'), (0.5, '0.5'), (0.6, '0.6'), (0.7, '0.7'), (0.8, '0.8'), (0.9, '0.9'), (1.0, '1.0')], verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='chatcontext',
            name='context',
            field=models.JSONField(default=list, verbose_name='Контекст'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='interestcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
