"""
Django settings for hsweb project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import environs
env = environs.Env()
env.read_env(env.str('ENV_PATH', '.env'))
# MODEL_ID = env('MODEL_ID')
# CHARACTER = env('CHARACTER')
# Paykassa params
PAYKASSA_SCI_ID = env.str('PAYKASSA_SCI_ID', 'WRONG_PAYKASSA_SCI_ID') 
PAYKASSA_SCI_KEY = env.str('PAYKASSA_SCI_KEY', 'WRONG_PAYKASSA_SCI_KEY')
PAYKASSA_DOMAIN = env.str('PAYKASSA_DOMAIN', 'WRONG_PAYKASSA_DOMAIN')

# Freekassa params
FREEKASSA_MERCHANT_ID = env.str('FREEKASSA_MERCHANT_ID', 'WRONG_FREEKASSA_MERCHANT_ID') 
FREEKASSA_API_KEY = env.str('FREEKASSA_API_KEY', 'WRONG_FREEKASSA_API_KEY') 
FREEKASSA_SECRET_1 = env.str('FREEKASSA_SECRET_1', 'WRONG_FREEKASSA_SECRET_1') 
FREEKASSA_SECRET_2 = env.str('FREEKASSA_SECRET_2', 'WRONG_FREEKASSA_SECRET_2') 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h8zp1_(qh$)pj)u29kpe#ky90d%usz#@c6q7=d+n6fn_#zqxqq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'investfing.life', '185.74.254.110','localhost','13.48.203.135', '83.220.175.36', 'dev.hellosissy.com', 'uat.hellosissy.com', 'hellocrissy.com', 'www.hellocrissy.com']

LOGIN_REDIRECT_URL = "chat"

# Application definition

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'hellosissy.com'
EMAIL_PORT = 25
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'welcome@hellosissy.com'
EMAIL_HOST_PASSWORD = 'Ab-1234567'


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'chat',
    'login',
    'my_magic_room',
    'payment',
    'users_chats',
    'user_management',
    'django_quill',
    'django_ckeditor_5',
]

ASGI_APPLICATION = 'hsweb.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_management.middleware.LastActivityMiddleware',
]

AUTH_USER_MODEL = 'user_management.User'

ROOT_URLCONF = 'hsweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hsweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES1 = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': '185.74.254.110', # For development
            # 'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# FOR DEVLOPMENT PURPOSES ON LOCAL MACHINE UNCOMMENT DATABASE CONFIG BELOW AND COMMENT ABOVE
#DATABASES = {
#      'default': {
#          'ENGINE': 'django.db.backends.postgresql',
#          'NAME': env('DB_NAME'),
#          'USER': env('DB_USER'),
#          'PASSWORD': env('DB_PASSWORD'),
#          'NAME': 'hs_dev',
#          'USER': 'dev_user',
#          'PASSWORD': 'DevP@ssw0rd!2023',
#         'HOST': '185.74.254.110',
#          'PORT': '5432',
#      }
#  }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [ os.path.join(BASE_DIR,'static') ]

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

NOWPAYMENTS_API_KEY='62DMNFS-FCDM4MH-HZVBYC5-K7P5HH2'
NOWPAYMENTS_IPN_KEY='3lWdY8yTpjfxhKIfnZW2a2kslqTxwKVm'
merchant001_API_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNHFiR21INnR3WERqdXZ0V1lBakIzTTVGcXAxIiwiZGF0ZSI6IjIwMjQtMTAtMTZUMTI6NDg6MTkuMDEzWiIsImlhdCI6MTcyOTA4Mjg5OX0.n91aqd732-2fgtYdPPW8ftICskwBcERy0iNHs97VK7I'

X_FRAME_OPTIONS = 'SAMEORIGIN'

QUILL_CONFIGS = {
    "default": {
        "theme": "snow",
        "modules": {
            "syntax": True,
            "toolbar": [
                [
                    {"font": []},
                    {"header": []},
                    {"align": []},
                    "bold",
                    "italic",
                    "underline",
                    "strike",
                    "blockquote",
                    # {"color": []},django_ckeditor_5_static
                    {"background": []},
                ],
                ["code-block", "link", "image", "video"],
                ["clean"],
            ],
            # quill-image-compress
            "imageCompressor": {
                "quality": 0.8,
                "maxWidth": 2000,
                "maxHeight": 2000,
                "imageType": "image/jpeg",
                "debug": False,
                "suppressErrorLogging": True,
            },
            # quill-resize
            "resize": {
                "showSize": True,
                "locale": {},
            },
        },
        "formats": [
            "bold", "italic", "underline", "strike", "code", "link", "image", "video", "background", "align"
        ],  # Добавлено поддержка 'align'
    },
    "simple": {
        "theme": "bubble",
        "modules": {
            "toolbar": [["bold", "italic"], ["clean"],
                        ["link", "image"],
                        ],
        },
    },
    "advanced": {
        "theme": "snow",
        "modules": {
            "toolbar": [
                [{"header": [1, 2, 3, False]}],
                ["bold", "italic", "underline", "strike"],
                [{"list": "ordered"}, {"list": "bullet"}],
                ["link", "image", "code-block"],
                ["clean"],
            ],
        },
    },
}


CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default':
        {
            'toolbar': 'full',
            'width': 'auto',
            'extraPlugins': ','.join([
                'codesnippet',
                'html5video',
            ]),
        },
}

# Настройки для CKEditor 5
customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

# CKEDITOR_5_CUSTOM_CSS = 'path_to.css' # optional
# CKEDITOR_5_FILE_STORAGE = "path_to_storage.CustomStorage" # optional
CKEDITOR_5_CONFIGS = {
    'default': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'heading6',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['undo', 'redo', 'fontSize', 'insertImage', 'mediaEmbed', 'removeFormat', 
                    '|', 'bold', 'italic', 'underline', 'strikethrough', 'alignment', 'link',
                    '|', 'sourceEditing', 'pageBreak', 'horizontalLine',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', '|',
                    'fontFamily', 'fontColor', 'fontBackgroundColor', 'highlight', 'heading', ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
        'mediaEmbed': {
            'previewsInData': True,  # Предпросмотр видео
        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        },
        'htmlSupport': {
            'allow': [
                {
                    'name': 'video',
                    'attributes': True,
                    'classes': True,
                    'styles': True
                },
                {
                    'name': 'source',
                    'attributes': True
                },
            ]
        },
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['undo', 'redo', 'heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        },
        'htmlSupport': {
            'allow': [
                {
                    'name': 'video',
                    'attributes': True,
                    'classes': True,
                    'styles': True
                },
                {
                    'name': 'source',
                    'attributes': True
                },
            ]
        },
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}

# Define a constant in settings.py to specify file upload permissions
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"  # Possible values: "staff", "authenticated", "any"

